Update README.md
lvimuser/lsp-inlayhints.nvim pull request #8
Opened 2022-08-01 21:29 UTC by bennypowers

Add TypeScript config example

2022-08-01 23:04 UTC, lvimuser requested changes
Afaik, you still need to pass `initializationOptions`. 
Can you add this?
```lua
init_options = {
  preferences = {
    importModuleSpecifierPreference = "relative",
    -- inlayHints
    -- https://github.com/typescript-language-server/typescript-language-server/blob/master/README.md#inlay-hints-typescriptinlayhints-experimental
    includeInlayParameterNameHints = "all",
    includeInlayParameterNameHintsWhenArgumentMatchesName = false,
    includeInlayFunctionParameterTypeHints = true,
    includeInlayVariableTypeHints = false,
    includeInlayPropertyDeclarationTypeHints = true,
    includeInlayFunctionLikeReturnTypeHints = true,
    includeInlayEnumMemberValueHints = true,
  },
}
```

Note that `VariableTypeHints` is purposely set to false, otherwise it becomes polluted very quickly.

2022-08-02 06:25 UTC, bennypowers commented
:shrug: this works for me, using `lspconfig`

https://github.com/bennypowers/dotfiles/blob/2b424b2d2c8240791f46cd463ccc793aa3f96f73/.config/nvim/lua/config/lsp-installer.lua#L215-L244

https://github.com/bennypowers/dotfiles/blob/2b424b2d2c8240791f46cd463ccc793aa3f96f73/.config/nvim/lua/config/lsp-installer.lua#L281

2022-08-02 14:22 UTC, lvimuser approved these changes

2022-08-02 14:22 UTC, lvimuser commented
Thanks!

2022-08-02 14:22 UTC, merged